import React, { useState } from "react";
import { Box, Typography, Button, Skeleton, Alert, Stack, Collapse } from "@mui/material";
import { AutoAwesome as AutoAwesomeIcon, Info as InfoIcon } from "@mui/icons-material";
import { aiApi } from "../../services/ai.api";

const SummaryWidget = ({ jobData }) => {
    const [summary, setSummary] = useState(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);

    const handleSummarize = async () => {
        setLoading(true);
        setError(null);
        try {
            const result = await aiApi.generateJobSummary(jobData);
            setSummary(result);
        } catch (err) {
            console.error("Summary generation failed:", err);
            // Default error message, handling the specific 429 inside if possible, 
            // but the interceptor might wrap it. The generic fallback is used if API fails.
            setError(err?.response?.data?.message || err.message || "AI Co-Pilot is currently unavailable. Displaying standard data.");
        } finally {
            setLoading(false);
        }
    };

    return (
        <Box sx={{ mt: 2, mb: 1, p: 2, borderRadius: "12px", border: "1px solid", borderColor: "divider", bgcolor: "background.paper" }}>
            <Box sx={{ display: "flex", alignItems: "center", justifyContent: "space-between", mb: summary || loading || error ? 2 : 0 }}>
                <Typography variant="subtitle2" fontWeight="600" sx={{ display: "flex", alignItems: "center", gap: 1 }}>
                    <AutoAwesomeIcon sx={{ color: "primary.main", fontSize: "1.2rem" }} />
                    AI Co-Pilot Summary
                </Typography>
                {!summary && !loading && (
                    <Button
                        size="small"
                        variant="outlined"
                        onClick={handleSummarize}
                        startIcon={<AutoAwesomeIcon />}
                        sx={{ borderRadius: "8px", textTransform: "none" }}
                    >
                        Summarize Case
                    </Button>
                )}
            </Box>

            <Collapse in={loading || !!error || !!summary}>
                {loading && (
                    <Stack spacing={1}>
                        <Skeleton variant="text" width="90%" animation="wave" />
                        <Skeleton variant="text" width="80%" animation="wave" />
                        <Skeleton variant="text" width="85%" animation="wave" />
                    </Stack>
                )}

                {error && (
                    <Alert severity="warning" icon={<InfoIcon />} sx={{ borderRadius: "8px" }}>
                        {error}
                    </Alert>
                )}

                {summary && !loading && !error && (
                    <Box sx={{ pl: 1 }}>
                        <ul style={{ margin: 0, paddingLeft: "20px", color: "var(--text-secondary)", fontSize: "0.875rem", lineHeight: 1.6 }}>
                            {summary.split('\n').filter(line => line.trim()).map((bullet, idx) => {
                                // Clean up the bullet points generated by AI (removing dashes if any, as <li> adds its own)
                                const cleanBullet = bullet.replace(/^[-•*]\s*/, "");
                                return <li key={idx}><strong>{cleanBullet}</strong></li>;
                            })}
                        </ul>
                    </Box>
                )}
            </Collapse>
        </Box>
    );
};

export default SummaryWidget;
